# HTTP server port
quarkus.http.port=8083

# application.properties
#quarkus.kafka.devservices.enabled=false

# Set global log level
quarkus.log.category."org.giant.resource".level=DEBUG



# Enable DevServices (default true, but make sure you didn?t disable it)
quarkus.kafka.devservices.enabled=false
kafka.bootstrap.servers=localhost:9092

# Incoming channel for completed transfers
mp.messaging.incoming.events-transfers-completed.connector=smallrye-kafka
mp.messaging.incoming.events-transfers-completed.topic=events-transfers-completed
mp.messaging.incoming.events-transfers-completed.value.deserializer=org.giant.dto.TransferEventDeserializer


# Incoming channel for failed transfers
mp.messaging.incoming.events-transfers-failed.connector=smallrye-kafka
mp.messaging.incoming.events-transfers-failed.topic=events-transfers-failed
mp.messaging.incoming.events-transfers-failed.value.deserializer=org.giant.dto.TransferEventDeserializer

##h2 database configuration
#quarkus.datasource.db-kind=h2
#quarkus.datasource.jdbc.url=jdbc:h2:mem:accountdb;DB_CLOSE_DELAY=-1
#quarkus.datasource.username=sa
#quarkus.datasource.password=lala
#quarkus.h2.console.enabled=true
#quarkus.h2.console.path=/h2-console

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/accountdb

# Hibernate ORM
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true